name: AI Match Summary Generator

on:
  schedule:
    # Run every 2 hours
    - cron: '*/20 * * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write # Needed to commit the JSON file

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install @google-cloud/text-to-speech

      - name: Create Google Credentials File
        env:
          GOOGLE_TTS_KEY: ${{ secrets.GOOGLE_TTS_KEY }}
        run: echo "$GOOGLE_TTS_KEY" | base64 -d > google_credentials.json

      - name: Run AI Generator Script
        env:
          AI_TOKEN: ${{ secrets.AI_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: google_credentials.json
          GOOGLE_TTS_KEY: ${{ secrets.GOOGLE_TTS_KEY }} # Used for check in script
        run: node scripts/generate_ai_summary.js

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ðŸ¤– Update AI Match Summaries [skip ci]"
          file_pattern: "src/data/*"
          add_options: "-A"
          repository: .
          branch: main
